### PR TITLE
SevenNet l3i5

### PR DESCRIPTION
**Pull request by YutackPark**
Update SevenNet-0 model to SevenNet-l3i5. I separated the submission directory from the previous SevenNet(-0), but most contents are the same. As discussed here (#168), we want to change our model name as SevenNet-l3i5.

Additional files:

1. $k_{\rm{SRME}}$ [results](https://www.dropbox.com/scl/fi/1a6sbwlsw5jalse6ik7x0/kSRME_sevennet.zip?rlkey=h68oir8xnch2zdgx19ldzyxbi&dl=0)
2. [Relaxed geometries](https://www.dropbox.com/scl/fi/kewudvzyw64h3dzjhudgg/cp_600.json.gz?rlkey=0mo0t4h3hu4gar9gah5zgzg0p&dl=0)

Result:
Model | # params | F1 | R2 | Missing preds | kSRME
-- | -- | -- | -- | -- | --
SevenNet-l3i5 | 1.171M | 0.76 | 0.776 | 3 | 0.5496

### CODE REVIEW

**Comment by janosh** [comment]
@YutackPark thanks for the new submission and congrats on the great $k_\rm{SRME}$ score!

do you mind if we put the new model in the same directory as the old model and differentiate them via separate YAML files for `sevennet-0.yml` and the new `sevennet-l3i5.yml`?

**Comment by YutackPark** [comment]
After re-run the benchmark to get relaxed structures, I have changed .csv.gz for consistency. The numbers are the same except for numerical differences.

Relaxed geometries: https://www.dropbox.com/scl/fi/kewudvzyw64h3dzjhudgg/cp_600.json.gz?rlkey=0mo0t4h3hu4gar9gah5zgzg0p&dl=0

**Comment by janosh** [comment]
@YutackPark thanks for the submission. looks like a nice performance bump on all metrics! 👍

just one thing missing. for reproducibility, could you share the script you used for the $k_{\rm{SRME}}$ evaluation?

**Comment by YutackPark** [comment]
@janosh, thanks for the effort! I really appreciate it.

For k_SRME, I'll provide the link here since the branch has already been merged:
https://www.dropbox.com/scl/fi/1a6sbwlsw5jalse6ik7x0/kSRME_sevennet.zip?rlkey=h68oir8xnch2zdgx19ldzyxbi&dl=0

This file contains the raw outputs of the K_SRME data along with the evaluation scripts. We obtained it from [MPA2suite/k_SRME GitHub repository](https://github.com/MPA2suite/k_SRME), and only replaced the potential used for evaluation.

Additionally, will both SevenNet models be kept in the leaderboard? Initially, I thought of replacing the old one with the new model.

**Comment by janosh** [comment]
thanks for sharing! i'll include this in the SevenNet l3i5 submission files.

> Additionally, will both SevenNet models be kept in the leaderboard? Initially, I thought of replacing the old one with the new model.

i think keeping both makes sense, at least for a while as it shows progress over time which is one of the goals of this project. the field is moving fast and it's easy to forget where it stood a year or two ago. keeping previous models around for a couple of years helps with that. i'm open to hearing other opinions though

**Pull request merged**
