### PR TITLE
Look at adding RMSD as a metric.

### PR DESCRIPTION
**Pull request by CompRhys**
For the forcefield methods we can also report the RMSD of the relaxed structure to the final structure as a metric. This would require us to store the final structures somewhere which may necessitate LFS.

### CODE REVIEW

**Comment by DanielYang59** [comment]
Hi @CompRhys sorry for the late response, just had a closer look and the following change should fix the `ptable_heatmap` issue.

https://github.com/janosh/matbench-discovery/blob/4d3d33f63a963f0d54f5538af04dd74866456c8f/data/wbm/eda_wbm.py#L81-L90

```diff
 ax_mp_cnt = pmv.ptable_heatmap(  # matplotlib version looks better for SI 
     elem_counts, 
-    fmt=lambda x, _: si_fmt(x, ".0f"),  # deprecated in favor of `value_fmt` because `fmt` is ambiguous
+    value_fmt=".0f",  # use `".0f"` directly for simplicity 
-    cbar_fmt=lambda x, _: si_fmt(x, ".0f"),  # deprecated in favor of `cbar_label_fmt` for similar reason above
+    cbar_label_fmt=".0f",
     zero_color="#efefef", 
     label_font_size=17, 
     value_font_size=14, 
     cbar_title=f"{dataset.upper()} Element Count", 
     log=(log := SymLogNorm(linthresh=100)), 
 ) 
```

I got the following:

[mp-element-counts-by-composition-symlog.pdf](https://github.com/user-attachments/files/16902304/mp-element-counts-by-composition-symlog.pdf)
[mp-element-counts-by-occurrence-symlog.pdf](https://github.com/user-attachments/files/16902307/mp-element-counts-by-occurrence-symlog.pdf)
[wbm-element-counts-by-composition-symlog.pdf](https://github.com/user-attachments/files/16902308/wbm-element-counts-by-composition-symlog.pdf)
[wbm-element-counts-by-occurrence-symlog.pdf](https://github.com/user-attachments/files/16902310/wbm-element-counts-by-occurrence-symlog.pdf)

Let me know if there is more issues.

**Comment by DanielYang59** [comment]
Quote from Janosh:
> if those custom kwargs fix the issue, we should make those values the new defaults.

Looks like the default values for `ptable_heatmap` is good now, i.e. simply removing both `fmt` (now `value_fmt`) and `cbar_fmt`(not `cbar_label_fmt`) args would generate proper quality plots (PDFs in above comment updated).

**Comment by janosh** [comment]
> Turns out the default for `ptable_heatmap` is good

thanks for pointing that out @DanielYang59! fixed in https://github.com/janosh/matbench-discovery/commit/c1f34dac228ef7f0da7598e99fe9be6db36198f5

**Comment by DanielYang59** [comment]
No problem!

**Comment by CompRhys** [comment]
Closing in favour of #152

**Pull request closed without merging**
