### PR TITLE
[WIP]Use src layout and move models directory into package

### PR DESCRIPTION
**Pull request by lan496**
This PR introduces src-layout because the editable install is not fully supported in the current flat-layout.

cf. https://setuptools.pypa.io/en/latest/userguide/development_mode.html#limitations
> Support for PEP 420-style implicit namespace packages for projects structured using flat-layout is still experimental. If you experience problems, you can try converting your package structure to the src-layout.

~~Also, when we install this package without editable, the `models/` directory is currently not included (introduced in https://github.com/janosh/matbench-discovery/pull/157).
This PR moves `models` back to `src/matbench_discovery` and fixes package-data access with [`importlib.resources`](https://importlib-resources.readthedocs.io/en/latest/using.html).~~

### CODE REVIEW

**Comment by janosh** [comment]
> This PR introduces src-layout because the editable install is not fully supported in the current flat-layout.

did you encounter install errors? if so, could you post them here for later reference? also, could you try

```sh
pip install -e . --config-settings editable-mode=compat
```

which is my go to install command since it helps VS Code IntelliSense resolve package imports. i believe this is a temporary workaround while the Python ecosystem is migrating from `setup.py/cfg` to `pyproject.toml` but could be wrong about that.

i'm generally not a fan of the `src` layout due to the added nesting it requires (resulting in longer file paths).

also, the `models/` directory is only meant to contain data files and scripts. so nothing should be imported from there which is why it was deliberately placed outside the package directory. moving it inside would mean all the model prediction `.csv.gz` files which are many MB in size would be uploaded to PyPI and downloaded as part of every `pip install matbench-discovery` which would make the package install quite slow

**Comment by janosh** [comment]
i should add that some people use matbench discovery only for some of the utility functions like `slurm_submit` and calc_energy_from_e_refs` with no intention of submitting models to the leaderboard. a fast and lean `pip install` without any data files would be good to keep for those people

**Comment by lan496** [comment]
Thanks for quick reply! Actually, I misunderstood `models/` directory and it will be fine.
Let me try your command for editable install.

**Comment by lan496** [comment]
When I tries `pip install -e .`, the package itself is installed, but code completion in ipython and VSCode did not work. On the other hand, when I've tried your suggested `pip install -e . --config-settings editable-mode=compat` ([a.k.a legacy behavior](https://setuptools.pypa.io/en/latest/userguide/development_mode.html)), the completion successfully works!

Thank you again. And I'll close this PR since my motivation is to use editable installation.

**Comment by janosh** [comment]
glad to hear that! i will better document this `pip install` variant so people don't need to struggle with unresolved imports

**Pull request closed without merging**
