### PR TITLE
Add MatterSim v1 5M

### PR DESCRIPTION
**Pull request by yanghan234**
Dear Developers,

Thank you for creating and maintaining this valuable benchmark set. We deeply appreciate the effort and dedication that have gone into its development.

I am submitting the performance of the _open-source_ model **MatterSim-V1** through this PR. The following changes have been made:

- [x] Replace `models/mattersim/mattersim.yml` with the performance metrics of the MatterSim-V1 5M model.
- [x] Added the relaxed structures and the predicted labels generated by the MatterSim-V1 5M model.

We hope this contribution enriches the benchmark set and fosters further advancements in the field. We look forward to the possibility of future collaboration.

Best regards,
Han

P.S.
Tagging my colleague @luzihen for awareness.

### CODE REVIEW

**Comment by janosh** [comment]
@yanghan234 thanks for the submission. could you also share the MatterSim v1 relaxed structures ([as compressed `pymatgen` JSON](https://matbench-discovery.materialsproject.org/contribute#--how-to-submit-a-new-model)) needed for the geometry optimization analysis on https://matbench-discovery.materialsproject.org/tasks/geo-opt

**Comment by yanghan234** [comment]
Hi @janosh, thanks for the comments. We are happy to share the final relaxed structures, but I did not find a clear instruction on how this should be done because it is going to be a large file. Would you let me know which way you prefer? Figshare? 
Also, I have saved the `trajectory.csv.gz` files for each of the structures, as instructured in your documentation (https://matbench-discovery.materialsproject.org/contribute#--how-to-submit-a-new-model). Should I compress them together into one single file or just submit a list of files seperately?  
Thank you!

**Comment by janosh** [comment]
Thanks! Feel free to share the final structures and trajectory file separately. Any download link will do. Figshare, dropbox, OneDrive, etc..

**Comment by yanghan234** [comment]
Hi @janosh, I have added the link to figshare. Please take look and let me know if you need further information to interpret these files.

**Comment by janosh** [comment]
thanks for the final relaxation trajectories! they are not stored with material IDs. i had to rely on order using file suffixes (000000, 000001, ...) in the compressed archive you shared to map back to material IDs. can you confirm the `Atoms` trajectories are stored in the same order as the index of the `wbm_summary.csv.gz`?

```py
import os
import tarfile
from io import BytesIO
from typing import Any

import pandas as pd

# unused import needed to parse string repr of Atoms with eval() below
from ase.atoms import Atoms  # noqa: F401
from pymatgen.io.ase import AseAtomsAdaptor
from pymatviz.enums import Key
from tqdm import tqdm

from matbench_discovery.data import df_wbm

# Path to the tar.gz archive
module_dir = os.path.dirname(__file__)
tgz_path = f"{module_dir}/2024-12-19-wbm-relax-traj-mattersim-v1-5M.tgz"

# Dictionary to store structures
structures_dict: dict[str, dict[str, Any]] = {}
ase_adaptor = AseAtomsAdaptor()

# Open and process the tar.gz archive
with tarfile.open(tgz_path, "r:gz") as tar:
    # Get list of CSV files in the archive
    extracted_dir = tar.getnames()[0]

    # Get all files in the archive
    all_members = tar.getmembers()
    # Filter for CSV files
    csv_members = [m for m in all_members if m.name.endswith(".csv.gz")]

    # Process each trajectory file
    for member in tqdm(csv_members, desc="Processing trajectory files"):
        # Extract material_id from filename
        file = os.path.basename(member.name)
        idx = int(file.split("_")[-1].split(".")[0])
        mat_id = df_wbm.iloc[idx][Key.mat_id]

        # Read the compressed CSV file directly from tar archive
        csv_gz_file = tar.extractfile(member)
        if csv_gz_file is None:
            raise ValueError(f"No CSV file found in {member.name}")
        df_i = pd.read_csv(BytesIO(csv_gz_file.read()))

        # Get the final structure (last row) from the 'Atoms' column
        final_atoms = eval(df_i["atoms"].iloc[-1])  # noqa: S307

        # Convert ASE Atoms to Pymatgen Structure
        structure = ase_adaptor.get_structure(final_atoms)

        # Store in dictionary with material_id as key
        structures_dict[mat_id] = structure.as_dict()

# Save to compressed JSON
pmg_json_path = "mattersim-v1-5M-relaxed-structures.json.gz"
pd.Series(structures_dict).to_json(pmg_json_path)


# %% reload from disk
srs_relaxed = pd.read_json(pmg_json_path, typ="series")
print(f"{len(srs_relaxed)=:,}")
```

would you care to update the [`test_mattersim.py`](https://github.com/yanghan234/matbench-discovery/blob/hanyang/update-mattersim/models/mattersim/test_mattersim.py) file as it loads and evaluates graphormer so will be inconsistent with the new results?

finally, could you allow me to force push to your fork? i resolved the merge conflicts locally but am unable to overwrite the git history in this PR

```
remote: Resolving deltas: 100% (36/36), completed with 11 local objects.
To https://github.com/yanghan234/matbench-discovery
 ! [remote rejected] pr/yanghan234/178 -> pr/yanghan234/178 (permission denied)
error: failed to push some refs to 'https://github.com/yanghan234/matbench-discovery'
```

**Comment by yanghan234** [comment]
Hi @janosh, sorry for the inconvenience. I have uploaded a new pickle file `mat_id_list.pkl` to figshare that contains the corresponding material ID of each trajectory in order. 

Also, I have allowed force push to my branch, and you may have a try to push your codes. Please let me know if it still does not work for you.

I will update the `test_mattersim.py` script once you push your codes there, just to prevent potential conflicts. 

Thank you!

**Comment by janosh** [comment]
thanks @yanghan234, still couldn't force push but re-resolved the file conflicts, this time using `git merge` instead of `git rebase` which allowed me to push. feel free to modify `test_mattersim.py`

**Comment by yanghan234** [comment]
Hi @janosh, I just updated the `test_mattersim.py` script. Please check it out and let me know if further modification needed. Thanks!

**Review by janosh — APPROVED** [review]
nice work, thanks a lot for this submission @yanghan234! glad to see MSR contributing back to the OSS community 👍

**Comment by chiang-yuan** [comment]
Just curious about what happened here. Does this PR just provide more detailed information on the same released M3GNet based checkpoint or the new model?

**Comment by yanghan234** [comment]
Thank you for your interest, @chiang-yuan!

This PR submits the performance of a newly released open-source checkpoint of MatterSim, replacing the previously used internal closed-source version from the last submission.

**Comment by chiang-yuan** [comment]
Thanks for the info @yanghan234! And this open-sourced new checkpoint is different from the one used in MatterSim preprint?

**Comment by yanghan234** [comment]
Hi @chiang-yuan, the preprint mainly used the open source 1M checkpoint. In the manuscript, we also used a transform-based architecture which was used in the previous submission to matbench-discovery, but it is not released yet. In this PR, the performance is the open source 5M checkpoint. We will submit the performance of 1M model shortly.

**Pull request merged**
